{% set version = "0.5" %}
{% set sha256 = "01d8ec200da67d6d54bb07630166a5449145a5dab10eb28c0671b71bce75ada5" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xarray !=0.8
    - sympy
    - pyparsing
    - tinydb
    - autograd
    - scipy
    - tqdm
    - dask >=0.10
    - distributed
    - numpy >=1.9
    - dill
  run:
    - python
    - matplotlib
    - pandas
    - xarray !=0.8
    - sympy
    - pyparsing
    - tinydb
    - autograd
    - scipy
    - tqdm
    - dask >=0.10
    - distributed
    - numpy >=1.9
    - dill

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
