{% set version = "0.8.2" %}
{% set sha256 = "e3cfea3c44f0c6e8fcffee2b1b0b1bb17996fd497cef215ab1a5812263b11c65" %}
package:
  name: pycalphad
  version: {{ version }}

source:
  fn: pycalphad-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pycalphad/pycalphad-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py2k]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xarray >=0.11.2
    - sympy ==1.5.1
    - pyparsing
    - tinydb >=3.8
    - scipy
    - numpy >=1.13
    - dill
    - cython >=0.24
    - cyipopt
    - python-symengine ==0.6.0
    - symengine ==0.6.0

  run:
    - python
    - matplotlib
    - pandas
    - xarray >=0.11.2
    - sympy ==1.5.1
    - pyparsing
    - tinydb >=3.8
    - scipy
    - {{ pin_compatible('numpy') }}
    - cython >=0.24
    - dill
    - cyipopt
    - python-symengine ==0.6.0
    - symengine ==0.6.0

test:
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot

about:
  home: https://pycalphad.org/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.
  doc_url: https://docs.pycalphad.org/
  dev_url: https://github.com/pycalphad/pycalphad

extra:
  recipe-maintainers:
    - richardotis
    - bocklund
