travis:
  secure:
    BINSTAR_TOKEN: FTfdNR8jvFkT21v/ihANH/KVrLxHN4GQ/6Pt+q0lamF9e1dXp7AJULwbIrhEiTGVI/8P64n4V1BbF803S7uWJSTeEjIi4HAb3dozJkmrtXgT/HymwZX9qgHbxal5fARQKRucoSOtUrbgr+Qg9vYPY45dVdi3odHa3+D9HVmM2qtBWD7YJ6w3XFjVCHC8lPFm/9zmNPtf8McCCL8L09ufVj2htjziNZzVCwGCxe6fP31zXFgQnvAT93QXM+xqOse38U9xIkdeLelyloysPUf72FO3du6kqXeeuNOoxWVqBAD6/oCnbw8+vP4AbjV3F6N9dIsHpwXgqLJYmZ81lVLe3KSN1ekfnbcJ5ubn0M8h3E4SCmFSvzTv6kadcwJdPyxbglgYRUDDHMIp6jFCH6hHpy/sb+bx8TALffIQ+fxJZALDsYurK/bWHhU1TQZ8ac5w6uld17YxB1PmdAcIvgVfg7ich+5oRSzhe6/OPR1fnVqbpdL5UG/Nr2TZeW4Cfp964SX9WgsLhKNWfwQ8z87ouLbIO2bxmVjTzxBNPQpCb6MN5gjZaqsvLRsH54j1twMa3hpz8e6EO+w4nEnHFrTF87E1Xcro/4rI+nku5RIEVeaP7bwMWxyOndMfm0RkSD97lKGzYriotpWn8LnlV98CWaS4iqXNFbdsNdjpG8W3LJI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
